[mgr]
keymap = [
	# Basic function
	{ on = "<Esc>", run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },
	{ on = "q",     run = "quit --no-cwd-file", desc = "Quit without outputting cwd-file" },
	{ on = "Q",     run = "quit",               desc = "Quit the process" },
	{ on = ".",     run = "hidden toggle",      desc = "Toggle the visibility of hidden files" },

	{ on = "o",     run = "open",               desc = "Open selected files" },

	# Vim navigation
	{ on = "h", run = "leave",		desc = "Back to the parent directory" },
	{ on = "j", run = "arrow next", desc = "Next file" },
	{ on = "k", run = "arrow prev", desc = "Previous file" },
	{ on = "l", run = "enter",		desc = "Enter the child directory" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "Go to top" },
	{ on = "G",          run = "arrow bot", desc = "Go to bottom" },

	# Goto
	{ on = [ "g", "h" ],		run = "cd ~",			desc = "Go home" },
	{ on = [ "g", "c" ],		run = "cd ~/.config",	desc = "Go ~/.config" },
	{ on = [ "g", "d" ],		run = "cd ~/downloads",	desc = "Go ~/downloads" },
	{ on = [ "g", "D" ],		run = "cd ~/documents",	desc = "Go ~/documents" },
	{ on = [ "g", "i" ],		run = "cd ~/images",	desc = "Go ~/images" },
	{ on = [ "g", "v" ],		run = "cd ~/videos",	desc = "Go ~/videos" },
	{ on = [ "g", "l" ],		run = "cd ~/link",		desc = "Go ~/link" },
	{ on = [ "g", "s" ],		run = "cd ~/school",	desc = "Go ~/school" },
	{ on = [ "g", "G" ],		run = "cd ~/games",		desc = "Go ~/games" },
	{ on = [ "g", "m" ],		run = "cd ~/music",		desc = "Go ~/music" },

	# Selection
	{ on = "<Space>",			run = [ "toggle", "arrow next" ],	desc = "Toggle the current selection state" },

	# Operation
	{ on = "d",					run = "remove",					desc = "Trash selected files" },
	{ on = [ "D", "D" ],		run = "remove --permanently",	desc = "Permanently delete selected files" },
	{ on = "y",					run = "yank",                   desc = "Yank selected files" },
	{ on = "x",					run = "yank --cut",             desc = "Yank selected files (cut)" },
	{ on = "p",					run = "paste",                  desc = "Put yanked files" },

	{ on = "Y",					run = "unyank",                 desc = "Cancel the yank status" },
	{ on = "X",					run = "unyank",                 desc = "Cancel the yank status" },

	{ on = "Z",					run = "plugin zoxide",          desc = "Jump to a directory via zoxide" },
	{ on = "m",					run = "create",					desc = "Create file or dir (ending with /)" },

	# Spot
	{ on = "i", run = "spot", desc = "Spot hovered file" },

	# Linemode
	{ on = [ "I", "s" ], run = "linemode size",        desc = "Display: size" },
	{ on = [ "I", "p" ], run = "linemode permissions", desc = "Display: permissions" },
	{ on = [ "I", "b" ], run = "linemode btime",       desc = "Display: btime" },
	{ on = [ "I", "m" ], run = "linemode mtime",       desc = "Display: mtime" },
	{ on = [ "I", "o" ], run = "linemode owner",       desc = "Display: owner" },
	{ on = [ "I", "n" ], run = "linemode none",        desc = "Display: none" },

	# Visual mode
	{ on = "v", run = "visual_mode",         desc = "Enter visual mode (selection mode)" },
	{ on = "V", run = "visual_mode --unset", desc = "Enter visual mode (deselection mode)" },

	# Seeking
	{ on = "K", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "J", run = "seek 5",  desc = "Seek down 5 units in the preview" },

	# Find
	{ on = "/", run = "find --smart",            desc = "Find next file" },
	{ on = "?", run = "find --previous --smart", desc = "Find previous file" },
	{ on = "n", run = "find_arrow",              desc = "Next found" },
	{ on = "N", run = "find_arrow --previous",   desc = "Previous found" },

	# Shell
	{ on = "w", run = 'shell -- swww img "$0"'},
]
